# Generated by Django 5.0.4 on 2026-04-05 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_subscriber_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="subscriber",
            field=models.ForeignKey(
                limit_choices_to={"role": "account"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
