# Generated by Django 5.0.4 on 2026-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_actor_timeline_event_new_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("contract_request", "Contract Request"),
                    ("contract_request_approved", "Contract Request Approved"),
                    ("contract_request_rejected", "Contract Request Rejected"),
                    ("contract_update", "Contract Update"),
                    ("chat_message", "Chat Message"),
                    ("new_email", "New Email"),
                    ("deadline_upcoming", "Deadline Upcoming"),
                    ("timeline_comment", "Timeline Comment"),
                    ("manager_alert", "Manager Alert"),
                    ("system", "System"),
                ],
                max_length=50,
            ),
        ),
    ]
