# Generated by Django 5.0.4 on 2026-04-08 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_tag_project_status_project_tags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_status_f023cb_idx",
            old_name="projects_pr_status_idx",
        ),
    ]
