# Generated by Django 5.0.4 on 2026-04-12 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0003_rename_projects_pr_status_idx_projects_pr_status_f023cb_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_timeline_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="deadline_reminder_days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TimelineComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("completion_confirmation", "Completion Confirmation"),
                            ("status_update", "Status Update"),
                            ("feedback", "Feedback"),
                            ("suggestion", "Suggestion"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.timelineevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
