# Generated by Django 5.0.4 on 2026-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_contractrequest_attachment_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="text_source",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pypdf", "pypdf (digital PDF)"),
                    ("textract", "AWS Textract (OCR)"),
                    ("manual", "Manual (pasted by user)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
