# Generated by Django 5.0.4 on 2026-04-08 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_organiser", "0002_incoming_email_and_ai_suggestions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="incomingemail",
            new_name="email_organ_project_347957_idx",
            old_name="email_organ_project_idx",
        ),
        migrations.RenameIndex(
            model_name="incomingemail",
            new_name="email_organ_receive_a0154a_idx",
            old_name="email_organ_recv_idx",
        ),
    ]
