# Generated by Django 5.0.4 on 2026-04-12 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "email_organiser",
            "0003_rename_email_organ_project_idx_email_organ_project_347957_idx_and_more",
        ),
        ("projects", "0004_timeline_comments_and_enhancements"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_topic", models.CharField(blank=True, max_length=30)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("risk_summary", models.TextField(blank=True)),
                ("contract_references", models.TextField(blank=True)),
                ("mitigation", models.TextField(blank=True)),
                ("suggested_response", models.TextField(blank=True)),
                ("resolution_path", models.TextField(blank=True)),
                ("timeline_impact", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "email analyses",
            },
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="category",
            field=models.CharField(
                choices=[
                    ("delay", "Delay"),
                    ("damage", "Damage"),
                    ("scope_change", "Change of Scope"),
                    ("costs", "Costs"),
                    ("delivery", "Delivery"),
                    ("compliance", "Compliance"),
                    ("quality", "Quality"),
                    ("dispute", "Dispute"),
                    ("general", "General"),
                    ("irrelevant", "Irrelevant"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="is_relevant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incomingemail",
            name="relevance",
            field=models.CharField(
                choices=[
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("none", "Not Relevant"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="incomingemail",
            index=models.Index(
                fields=["category"], name="email_organ_categor_909542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingemail",
            index=models.Index(
                fields=["relevance"], name="email_organ_relevan_6ba37a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingemail",
            index=models.Index(
                fields=["is_resolved"], name="email_organ_is_reso_50968a_idx"
            ),
        ),
        migrations.AddField(
            model_name="emailanalysis",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="email_organiser.incomingemail",
            ),
        ),
        migrations.AddField(
            model_name="emailanalysis",
            name="generated_timeline_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_email_analyses",
                to="projects.timelineevent",
            ),
        ),
    ]
