from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models


class Tag(models.Model):
    """Free-form, user-defined label that projects can attach (priority, theme, etc.)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64, unique=True)
    # Hex colour code, e.g. "#EF4444". Tailwind-friendly default (gray-500).
    color = models.CharField(max_length=7, default="#6B7280")
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_tags",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Project(models.Model):
    ACTIVE = "active"
    COMPLETED = "completed"
    ARCHIVED = "archived"

    STATUS_CHOICES = [
        (ACTIVE, "Active"),
        (COMPLETED, "Completed"),
        (ARCHIVED, "Archived"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.CASCADE,
        related_name="projects",
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    # Auto-generated by ProjectListCreateView.perform_create — never user-supplied.
    generic_email = models.EmailField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ACTIVE)
    tags = models.ManyToManyField(Tag, blank=True, related_name="projects")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=["account"]),
            models.Index(fields=["status"]),
        ]

    def __str__(self) -> str:
        return self.name


class ProjectMembership(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="memberships")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="project_memberships",
    )
    joined_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("project", "user")

    def __str__(self) -> str:
        return f"{self.user} — {self.project}"


class Timeline(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.OneToOneField(Project, on_delete=models.CASCADE, related_name="timeline")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"Timeline for {self.project}"


class TimelineEvent(models.Model):
    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"

    STATUS_CHOICES = [
        (PLANNED, "Planned"),
        (IN_PROGRESS, "In Progress"),
        (COMPLETED, "Completed"),
    ]

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    PRIORITY_CHOICES = [
        (LOW, "Low"),
        (MEDIUM, "Medium"),
        (HIGH, "High"),
        (CRITICAL, "Critical"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    timeline = models.ForeignKey(Timeline, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PLANNED)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default=MEDIUM)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_timeline_events",
    )
    # How many days before end_date to fire a DEADLINE_UPCOMING notification.
    # Defaults to 3; the project creator can adjust per-event.
    deadline_reminder_days = models.PositiveIntegerField(default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["start_date"]

    def __str__(self) -> str:
        return self.title


class TimelineComment(models.Model):
    """Comments on timeline events — used by invitees to confirm completion,
    provide feedback, or make suggestions."""

    GENERAL = "general"
    COMPLETION_CONFIRMATION = "completion_confirmation"
    STATUS_UPDATE = "status_update"
    FEEDBACK = "feedback"
    SUGGESTION = "suggestion"

    COMMENT_TYPE_CHOICES = [
        (GENERAL, "General"),
        (COMPLETION_CONFIRMATION, "Completion Confirmation"),
        (STATUS_UPDATE, "Status Update"),
        (FEEDBACK, "Feedback"),
        (SUGGESTION, "Suggestion"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event = models.ForeignKey(
        TimelineEvent, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="timeline_comments",
    )
    content = models.TextField()
    comment_type = models.CharField(
        max_length=30, choices=COMMENT_TYPE_CHOICES, default=GENERAL
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self) -> str:
        return f"Comment by {self.author} on {self.event}"
