# Generated by Django 5.0.4 on 2026-04-20 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0004_timeline_comments_and_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISuggestionFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("suggestion", "Suggestion"),
                            ("timeline_event", "Timeline Event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("rating", models.SmallIntegerField(choices=[(1, "Up"), (-1, "Down")])),
                ("reason", models.TextField(blank=True, max_length=500)),
                ("model", models.CharField(max_length=64)),
                ("provider", models.CharField(default="anthropic", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="feedback_ai_target__b41819_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="feedback_ai_project_d2bc26_idx",
                    ),
                ],
                "unique_together": {("user", "target_type", "target_id")},
            },
        ),
    ]
