# Generated by Django 5.0.4 on 2026-04-22 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('projects', '0004_timeline_comments_and_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_feedback', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feature_key', 'created_at'], name='feedback_fe_feature_908122_idx'), models.Index(fields=['project', 'feature_key'], name='feedback_fe_project_6367e0_idx')],
                'unique_together': {('user', 'feature_key', 'project')},
            },
        ),
    ]
